"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_api_account
from dm_api_account.model.user import User
globals()['User'] = User
from dm_api_account.model.user_envelope import UserEnvelope


class TestUserEnvelope(unittest.TestCase):
    """UserEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserEnvelope(self):
        """Test UserEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
